### ISSUE TITLE
Docker Container not starting

### ISSUE THREAD

**Issue by alkanlab** [passwall/passwall-server#187]
**Describe the bug**
Hi,

I got an issue while starting Passwall server. I have actual docker-compose file, I added two service in it for Passwall Server and Postgres. Postgres is working healty but Passwall Server is looping on restarting.

**You can find the error logs from the container:**
```log
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
```

**Docker-Compose File**
```yaml
  passwall-db:
    container_name: passwall-db
    image: postgres:alpine
    hostname: passwall-db
    networks:
      saasnet:
        aliases:
        - passwall-db
    restart: on-failure
    env_file:
    - passwall.env
    volumes:
    - /root/docker/passwall-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  passwall-server:
    container_name: passwall-server
    image: passwall/passwall-server:latest
    hostname: passwall-server
    networks:
      saasnet:
        aliases:
        - passwall-server
    restart: always
    env_file:
    - passwall.env
    build:
      context: .
    depends_on:
      passwall-db:
        condition: service_healthy
    volumes:
    - /root/docker/passwall-server:/app/config
```
**OS Verison**
```sh
root@xxx:~/docker# uname -a
Linux xxx 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@xxx:~/docker# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
root@xxx:~/docker# 
```
**Docker Verison**
```sh
root@xxx:~/docker# docker version
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:29 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
   o version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
   ersion:          0.19.0
  GitCommit:        de40ad0

root@xxx:~/docker# docker compose -verison
docker-compose version 1.29.2, build 5becea4c
```
If you need any further logs please don't hesitate to contact me.

Thanks.Regards
